# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- task: SSH@0
  inputs:
    sshEndpoint: 'Linode abvogel.com server'
    runOptions: 'inline'
    inline: |
      cd /var/www/html
      pwd
      git pull
      id -u -n
      hexo generate
      ~/.nvm/versions/node/v12.8.0/bin/hexo generate
      ~/.nvm/versions/node/v12.8.0/bin/hexo publish